export enum RoleName {
  PATIENT = 'Patient',
  DOCTOR = 'Doctor',
  ADMIN = 'Admin',
  SUPER_ADMIN = 'Super Admin',
}

export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SLOT_NOT_AVAILABLE = 'SLOT_NOT_AVAILABLE',
  SLOT_ALREADY_BOOKED = 'SLOT_ALREADY_BOOKED',
  APPOINTMENT_NOT_FOUND = 'APPOINTMENT_NOT_FOUND',
  INVALID_APPOINTMENT_STATUS = 'INVALID_APPOINTMENT_STATUS',
  DOCTOR_SELF_BOOKING = 'DOCTOR_SELF_BOOKING',
  PAST_APPOINTMENT = 'PAST_APPOINTMENT',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  OPTIMISTIC_LOCK_FAILURE = 'OPTIMISTIC_LOCK_FAILURE',
  CANCELLATION_NOT_ALLOWED = 'CANCELLATION_NOT_ALLOWED',
  RESCHEDULE_NOT_ALLOWED = 'RESCHEDULE_NOT_ALLOWED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  DOCTOR_NOT_FOUND = 'DOCTOR_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  CONSULTATION_NOT_FOUND = 'CONSULTATION_NOT_FOUND',
  INVALID_CONSULTATION_STATUS = 'INVALID_CONSULTATION_STATUS',
  PRESCRIPTION_NOT_FOUND = 'PRESCRIPTION_NOT_FOUND',
  PRESCRIPTION_CANCELLED = 'PRESCRIPTION_CANCELLED',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  WEBHOOK_VERIFICATION_FAILED = 'WEBHOOK_VERIFICATION_FAILED',
  WEBHOOK_DUPLICATE = 'WEBHOOK_DUPLICATE',
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
}

export const REQUEST_ID_HEADER = 'x-request-id';
export const CORRELATION_ID_HEADER = 'x-correlation-id';
export const IDEMPOTENCY_KEY_HEADER = 'idempotency-key';

export const AUDIT_ACTIONS = {
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGOUT_ALL: 'LOGOUT_ALL',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  PASSWORD_RESET: 'PASSWORD_RESET',
  FAILED_LOGIN: 'FAILED_LOGIN',
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  ROLE_CHANGE: 'ROLE_CHANGE',
  APPOINTMENT_BOOKED: 'APPOINTMENT_BOOKED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED: 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_COMPLETED: 'APPOINTMENT_COMPLETED',
  BOOKING_FAILED: 'BOOKING_FAILED',
  CONSULTATION_STARTED: 'CONSULTATION_STARTED',
  CONSULTATION_COMPLETED: 'CONSULTATION_COMPLETED',
  NOTES_UPDATED: 'NOTES_UPDATED',
  PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
  PRESCRIPTION_UPDATED: 'PRESCRIPTION_UPDATED',
  PRESCRIPTION_CANCELLED: 'PRESCRIPTION_CANCELLED',
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_CAPTURED: 'PAYMENT_CAPTURED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED',
} as const;

export const OUTBOX_EVENTS = {
  APPOINTMENT_BOOKED: 'AppointmentBooked',
  APPOINTMENT_CANCELLED: 'AppointmentCancelled',
  APPOINTMENT_RESCHEDULED: 'AppointmentRescheduled',
  APPOINTMENT_COMPLETED: 'AppointmentCompleted',
  CONSULTATION_STARTED: 'ConsultationStarted',
  CONSULTATION_COMPLETED: 'ConsultationCompleted',
  PRESCRIPTION_CREATED: 'PrescriptionCreated',
  PRESCRIPTION_UPDATED: 'PrescriptionUpdated',
  PRESCRIPTION_CANCELLED: 'PrescriptionCancelled',
  PAYMENT_CAPTURED: 'PaymentCaptured',
} as const;

export const QUEUE_NAMES = {
  OUTBOX: 'outbox-events',
  NOTIFICATIONS: 'notifications',
  PAYMENTS: 'payments',
  PRESCRIPTION_PDF: 'prescription-pdf',
  DLQ: 'dead-letter',
} as const;

export const JOB_NAMES = {
  POLL_OUTBOX: 'poll-outbox',
  SEND_NOTIFICATION: 'send-notification',
  PROCESS_WEBHOOK: 'process-webhook',
  GENERATE_PRESCRIPTION_PDF: 'generate-prescription-pdf',
} as const;
